### ISSUE TITLE
AttributeError: module 'streamlit.runtime.state.widgets' has no attribute 'compute_widget_id'

### ISSUE THREAD

**Issue by mabusdogma** [PaleNeutron/streamlit-ext#7]
Hello! I just got an error with this new version of streamlit from today:

```
2023-08-27 11:00:24.860 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "C:\Automations\Main.py", line 4, in <module>
    import streamlit_ext as ste
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit_ext\__init__.py", line 1, in <module>
    from .container import DummySidebar
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit_ext\container.py", line 6, in <module>
    from . import paramed_element
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit_ext\paramed_element.py", line 24, in <module>
    super_get_widget_id = getattr(stw, _get_widget_id_func)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'streamlit.runtime.state.widgets' has no attribute 'compute_widget_id'
```

**Comment by PaleNeutron** [comment]
Should be some breaking changes in latest streamlit. I'll fix it ASAP
